#4: Rust API unit tests
ripe-tech/pconvert-rust pull request #36
Opened 2021-01-19 16:40 UTC by joao-conde

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/pconvert-rust/issues/4 |
| Dependencies | None |
| Decisions | In this PR, we make the command-line "tests" we had also runnable via `cargo test`. The code to execute is the same, hence we refactor common code into tests and use it in the command-line binary. Note that the reverse can't be done because the `cli.rs` file is not part of the crate: it is merely a binary. Thus, `cli.rs` can use code from our lib (like the testing code) but the reverse can't be done. Regardless, it makes more sense to me to have testing code in the test module, and, because we want to, to provide the same testing code via command-line, resembling the original `pconvert` |
| Screenshot | ![image](https://user-images.githubusercontent.com/16060539/105064773-0cf52d00-5a75-11eb-8eca-195aa5586980.png) |

2021-02-05 12:52 UTC, gcandal approved these changes

2021-02-05 15:39 UTC, joao-conde commented
Re-assigning to me and all of the other `pconvert_rust` unit tests PR as CI started failing.

2021-02-05 15:52 UTC, joao-conde commented
It is the same problem across all PRs: it is a compilation failure of `wasm-pack` (not a project dependency, just the tool used to build the wasm module) with rust version 1.40

2021-02-09 09:06 UTC, joamag commented
@joao-conde please re-add the CLI features we want to make this compatible with the original convert, you can keep the test code. We can be redundant in the code no problem

2021-02-09 09:07 UTC, joamag commented
adding fast-track to try to close this as soon as possible.
Let's also avoid unneeded refactor of the code, and instead use separate PRs for that

2021-02-09 09:39 UTC, joao-conde commented
@joamag  the CLI test options still exist, just like in pconvert

2021-02-09 10:11 UTC, joamag requested changes

2021-02-09 10:11 UTC, joamag commented on src/cli.rs
> +use pconvert_rust::test::{apply_blue_filter, compose, compose_parallel, Background};
let's move this stuff from the test namespace and to something better like `utils` or `compose`

2021-02-09 10:11 UTC, joamag commented
@joao-conde move that stuff into a better place

2021-02-09 10:45 UTC, joao-conde commented
Btw CI failing because of https://github.com/rustwasm/wasm-pack/issues/969

2021-02-09 12:14 UTC, joamag approved these changes

2021-02-09 12:14 UTC, merged